<?php

/**
 * @file
 * Contains dgddi_sso.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dgddi_sso_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dgddi_sso module.
    case 'help.page.dgddi_sso':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DGDDI SSO Propagation') . '</p>';
      return $output;

    default:
  }
}
